### ISSUE TITLE
Error while adding roles

### ISSUE THREAD

**Issue by Mitch-Altman** [greys-bots/form-fox#23]
Dear dev, 

The bot doesn’t add roles when accepting. Could you help me with this? 

It has all the required rights etc. 

When I accept someone I get this message;

Err while adding roles: Supplied Array or Collection roles includes an invalid element: [object Object]

**Comment by selenated** [comment]
Hmm, that's strange... Can you list the form's roles with `ff!roles [form id]` and send the output?

**Comment by Mitch-Altman** [comment]
Dear,

Thanks for responding, means alot 💪🏼




Op do 13 jan. 2022 om 14:33 schreef Grey Himmel ***@***.***>

**Comment by Mitch-Altman** [comment]
Found the issue sir,

The role Form Fox needs to be higher than the role it needs to give, I’m
sorry for causing this unnecessarily issue making.

Op do 13 jan. 2022 om 14:33 schreef Grey Himmel ***@***.***>

**Comment by selenated** [comment]
It's alright, no worries ^^
Glad things are working now! I'll go ahead and close this, but feel free to re-open if the problem comes up again

**Comment by Mitch-Altman** [comment]
Absolutely will do, have one other question;

When I received a filled in form it gives me also the option for a ticket.
When hitting this reaction button it says there is no ticket channel set.
But when I use ff!help there is no command to see how to set that up.

Is this purely just a missing command in the help embed or is there
something I’m not seeing 😂?



Op do 13 jan. 2022 om 15:29 schreef Grey Himmel ***@***.***>

**Comment by selenated** [comment]
Due to the switch to slash commands, some commands are only available using those right now- the one for setting up a ticket category is currently an example 😅
You can use `/config ticketcategory` to set one for now! I'm also working on an update that'll allow you to set a message that the bot will automatically send for when tickets are opened

**Comment by Mitch-Altman** [comment]
Awesome, thanks! I’ll keep an eye out for that update! 💪🏼💪🏼

Op do 13 jan. 2022 om 15:35 schreef Grey Himmel ***@***.***>

**Comment by Mitch-Altman** [comment]
Well, the bot doesn’t react on those / commands.. so I’ll wait on the
update as said. Thanks for the support, much appreciated

Op do 13 jan. 2022 om 15:35 schreef Grey Himmel ***@***.***>

**Comment by selenated** [comment]
Hrmm, that might be a permissions issue with the app commands. Can you try using [this link](https://discord.com/oauth2/authorize?client_id=737192331241062462&permissions=268561472&scope=bot%20applications.commands) and inviting the bot to your server again? No need to kick it first, this just adds the permission to use slash commands for the bot

**Comment by Mitch-Altman** [comment]
Yes, that worked great!! slash commands now work.

Only thing is, I tried to set up a new form again because the error message
I'm getting on accepting a form says:  ERR! Response accepted, but couldn't
message the user! and ERR! Cannot read property 'name' of undefined
(Response still accepted!) To be fair: it sent me the form in pm, the
denial message too, including the reason. But the accepted message is not
being sent after I reinvited the bot. and when you hit the ticket button,
the channel gets created but there is no way to close the ticket than or
something similar. any idea how this could be solved?

Op do 13 jan. 2022 om 15:41 schreef Grey Himmel ***@***.***>:

**Comment by selenated** [comment]
Just pushed an update that should fix the acceptance message, sorry about that 😅
As for the issue with messaging users, that's an error on Discord's end- it's not really something that I can fix unfortunately. Usually the issue is the user who sent in a response having their DMs closed for the server, though having DMs with the bot should negate that, so I'm not sure what the issue is :(

For the tickets, right now the only way to close them is by deleting the channel manually or accepting/denying a response (which automatically deletes the channel). I'm planning on adding more to that, but right now I'm a bit worried about feature creep so to speak, since I have another bot that's specifically made for tickets ^^'

**Comment by Mitch-Altman** [comment]
I completely understand!

 Accept messages in dm are getting sent and received, so thanks for that!
I do get a new error message that says: Err while adding roles: Supplied
Array or Collection roles includes an invalid element: [object Object] -
but the message still gets delivered of the accepting and the role gets
added too. So in my opinion this works for me now 100 %

You and your bot are a lifesaver for me at this point!

greets,

Mitch..

ps.. if you need help with testing and the back and forth we just did, hit
me up.. always glad to help

Op do 13 jan. 2022 om 16:44 schreef Grey Himmel ***@***.***>:

**Comment by selenated** [comment]
Glad you're enjoying the bot! And thanks for offer to help test, honestly I need to work on setting up a proper way for people to test new things before they go live :'D
I'll take another look at roles in a bit and see if I can figure out where the error is coming from. Thanks for helping me hammer out these issues!

**Comment by Mitch-Altman** [comment]
No worries, thanks for the update!

Op do 13 jan. 2022 om 16:53 schreef Grey Himmel ***@***.***>
